name: deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '16.x'

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: prhosting.hu
          port: 22
          username: alphaws
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: whoami
