name: deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '16.x'

      - name: Add ssh
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: 'SSH: TRUST HOSTS'
        run: |
          ssh-keyscan prhosting.hu >> ~/.ssh/known_hosts

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: prhosting.hu
          username: alphaws
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: whoami
